import type { Metadata } from "next";
import dynamic from "next/dynamic";
import Link from "next/link";
import ToolNavBar from "../components/ToolNavBar";

const faqs = [
  {
    q: "What is a good ROI for options trading?",
    a: "A 'good' ROI depends heavily on the strategy and duration. For short-term options trades (under 30 days), many traders target 2–5% ROI per trade. What matters more is the annualized ROI — a 3% ROI on a 14-day trade annualizes to over 78%, which is strong compared to most asset classes.",
  },
  {
    q: "What is annualized ROI and why does it matter?",
    a: "Annualized ROI scales your trade's return to a full year, allowing fair comparisons between trades of different durations. A 2% return in 10 days annualizes to ~73%, while a 10% return in 180 days annualizes to ~20%. Annualized ROI helps you prioritize which trades best use your capital over time.",
  },
  {
    q: "What is 'Premium per Day' in options trading?",
    a: "Premium per Day is the daily cash flow generated by your position — the total premium divided by the trade duration. It's useful for theta-based strategies (selling covered calls or cash-secured puts) where you want to know how much time value you collect each day.",
  },
  {
    q: "How is options ROI different from stock ROI?",
    a: "Stock ROI is straightforward: gain divided by cost. Options ROI uses the collateral or margin required as the denominator, not the option premium itself. This reflects your actual capital at risk — especially important for strategies like cash-secured puts where you tie up significant buying power.",
  },
  {
    q: "Can I compare ROI between trades with different durations?",
    a: "Not directly — that's why annualized ROI exists. A 30-day trade with 3% ROI and a 60-day trade with 5% ROI look similar on raw ROI, but annualize to ~36% vs ~30%. Always use annualized ROI when comparing trades with different holding periods.",
  },
];

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map(({ q, a }) => ({
    "@type": "Question",
    name: q,
    acceptedAnswer: { "@type": "Answer", text: a },
  })),
};

const ROICalculator = dynamic(() => import("../ROICalculator"), { ssr: false });

export const metadata: Metadata = {
  title: "Options ROI Calculator",
  description:
    "Calculate the return on investment for your options trades. Track multiple positions by ticker, premium received, and holding duration to compare performance across your portfolio.",
  alternates: { canonical: "/roi-calculator" },
  openGraph: {
    title: "Options ROI Calculator | TradeToolsHub",
    description:
      "Calculate the return on investment for your options trades. Track multiple positions and compare premiums.",
    url: "https://www.tradetoolshub.com/roi-calculator",
  },
};

export default function Page() {
  const currentYear = new Date().getFullYear();
  return (
    <div className="min-h-screen bg-gray-900 text-white flex flex-col items-center p-4">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />
      <header className="w-full max-w-4xl text-center py-6">
        <Link href="/" className="text-teal-400 text-sm hover:underline mb-4 inline-block">
          ← All Tools
        </Link>
        <h1 className="text-4xl md:text-5xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-teal-400 to-teal-200">
          Options ROI Calculator
        </h1>
        <p className="text-lg text-gray-400 mt-2">
          Track and compare return on investment across your options positions.
        </p>
      </header>
      <ToolNavBar />
      <main className="w-full max-w-4xl">
        <ROICalculator />
      </main>
      <section className="w-full max-w-4xl mt-10 mb-4">
        <h2 className="text-xl font-bold text-gray-200 mb-5">Frequently Asked Questions</h2>
        <div className="space-y-3">
          {faqs.map(({ q, a }, i) => (
            <div key={i} className="bg-gray-800 rounded-lg p-5 border border-gray-700">
              <h3 className="text-sm font-semibold text-teal-400 mb-2">{q}</h3>
              <p className="text-gray-400 text-sm leading-relaxed">{a}</p>
            </div>
          ))}
        </div>
      </section>
      <section className="w-full max-w-4xl mt-6 mb-4">
        <h2 className="text-lg font-bold text-gray-300 mb-4">Related Tools</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <Link href="/breakeven-calculator" className="group bg-gray-800 rounded-lg p-4 border border-gray-700 hover:border-teal-500 transition-colors">
            <p className="font-semibold text-teal-400 group-hover:text-teal-300 text-sm">Breakeven Calculator</p>
            <p className="text-gray-500 text-xs mt-1">Find the price your trade needs to reach to break even.</p>
          </Link>
          <Link href="/margin-calculator" className="group bg-gray-800 rounded-lg p-4 border border-gray-700 hover:border-teal-500 transition-colors">
            <p className="font-semibold text-teal-400 group-hover:text-teal-300 text-sm">Margin Calculator</p>
            <p className="text-gray-500 text-xs mt-1">Understand how leverage amplifies your returns and losses.</p>
          </Link>
        </div>
      </section>
      <footer className="w-full max-w-4xl text-center mt-auto py-8 text-gray-500 text-sm">
        <div className="border-t border-gray-700 pt-4">
          <p className="font-medium text-red-400">RISK DISCLAIMER:</p>
          <p className="text-xs mt-1 max-w-2xl mx-auto">
            The calculators and tools provided on this website are for informational and educational
            purposes only. They are not intended as financial advice. All investments, including
            options trading, involve risk. Please consult with a qualified financial advisor before
            making any investment decisions.
          </p>
        </div>
        <div className="mt-4">&copy; {currentYear} TradeToolsHub. All Rights Reserved.</div>
        <div className="mt-1 text-xs text-gray-600">Powered by Next.js and Tailwind CSS.</div>
      </footer>
    </div>
  );
}
